name:                yi-intero
version:             0.14.0
synopsis:            Intero support for Yi
#description:
homepage:            https://github.com/noughtmare/yi-intero#readme
license:             GPL-2
author:              Jaro Reinders
maintainer:          noughtmare@openmailbox.org
copyright:           2017 Jaro Reinders
category:            Yi
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - binary
  - data-default
  - process
  - transformers-base
  - yi-rope
  - text
  - yi-core     == 0.14.*
  - yi-language == 0.14.*

library:
  source-dirs: src
  exposed-modules: 
    - Yi.Intero